<?php
/**
 * @category    M2Commerce Enterprise
 * @package     M2Commerce_BulkAddToCart
 * @copyright   Copyright (c) 2023 M2Commerce Enterprise
 * @author      dawoodgondaldev@gmail.com
 */

/**
 * @var \Magento\Catalog\Block\Product\ProductList\Toolbar $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \M2Commerce\BulkAddToCart\Helper\SessionHelper $sessionHelper
 */

$sessionHelper = $this->helper(\M2Commerce\BulkAddToCart\Helper\SessionHelper::class);
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= $escaper->escapeHtml(__('Sort By')) ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
            <option value="<?= $escaper->escapeHtmlAttr($_key) ?>"
                <?php if ($block->isOrderCurrent($_key)) :?>
                    selected="selected"
                <?php endif; ?>
            >
                <?= $escaper->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <?php if ($block->getCurrentDirection() == 'desc') :?>
        <a title="<?= $escaper->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
           href="#"
           class="action sorter-action sort-desc"
           data-role="direction-switcher"
           data-value="asc">
            <span><?= $escaper->escapeHtml(__('Set Ascending Direction')) ?></span>
        </a>
    <?php else :?>
        <a title="<?= $escaper->escapeHtmlAttr(__('Set Descending Direction')) ?>"
           href="#"
           class="action sorter-action sort-asc"
           data-role="direction-switcher"
           data-value="desc">
            <span><?= $escaper->escapeHtml(__('Set Descending Direction')) ?></span>
        </a>
    <?php endif; ?>

    <?php if ($sessionHelper->isBulkAddToCartEnable()) :?>
        <button type="button" id="add-all-to-cart-button" class="bulk-add-to-cart" data-role="bulk-addtocart">Add All Items to Cart</button>
        <script type="text/x-magento-init">
            {
                "#add-all-to-cart-button": {
                    "bulkAddToCart": {}
                }
            }
        </script>
    <?php endif; ?>
</div>

