<?php
/**
 * @category    M2Commerce Enterprise
 * @package     M2Commerce_BulkAddToCart
 * @copyright   Copyright (c) 2023 M2Commerce Enterprise
 * @author      dawoodgondaldev@gmail.com
 */

/**
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<?php if ($block->getCollection()->getSize()) :?>
    <?php $widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($block->getWidgetOptionsJson());
        $widgetOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['productListToolbarForm']);
    ?>
    <div class="toolbar toolbar-products" data-mage-init='{"productListToolbarForm":<?= $widgetOptions ?>}'>
        <?php if ($block->isExpanded()) :?>
            <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
        <?php endif; ?>

        <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>

        <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>

        <?php if ($block->isExpanded()) :?>
            <?php include ($block->getTemplateFile('M2Commerce_BulkAddToCart::product/list/toolbar/sorter.phtml')) ?>
        <?php endif; ?>

        <?= $block->getPagerHtml() ?>
    </div>
<?php endif ?>
